# Generated by Django 3.2.6 on 2023-08-28 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(blank=True, max_length=150)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('ordered_at', models.DateField(default=datetime.datetime(2023, 8, 28, 16, 43, 59, 628917))),
                ('ordered', models.BooleanField(default=False)),
                ('consultant', models.TextField(blank=True, max_length=300, null=True)),
                ('consultation_fees', models.DecimalField(decimal_places=2, default=200.0, max_digits=20, null=True)),
                ('procedure_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('department', models.TextField(blank=True, max_length=300, null=True)),
                ('payment_mode', models.TextField(blank=True, default='Cash', max_length=100, null=True)),
                ('physiotherapy_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patients',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='drug_imprint',
        ),
        migrations.AddField(
            model_name='stock',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='company_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='complement',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='discount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='distributor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='distributor_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='packing',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='trading_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='1', null=True)),
                ('taken', models.CharField(blank=True, max_length=300, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('drug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.stock')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.patients'),
        ),
    ]
