# Generated by Django 3.2.6 on 2023-08-15 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('ordered_at', models.DateField(default=datetime.datetime(2023, 8, 15, 17, 21, 11, 546763))),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.patients')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='1', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('drug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.stock')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pharmacy.order')),
            ],
        ),
    ]
