# Generated by Django 3.2.6 on 2023-08-17 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20230817_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 10, 12, 3, 166161)),
        ),
    ]
