# Generated by Django 3.2.6 on 2023-08-22 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_auto_20230823_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='taken',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 0, 58, 22, 807893)),
        ),
    ]
