# Generated by Django 3.2.6 on 2023-08-23 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_auto_20230823_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 12, 6, 40, 420832)),
        ),
    ]
