# Generated by Django 3.2.6 on 2023-08-23 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_auto_20230823_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consultation_fees',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 12, 58, 12, 930171)),
        ),
        migrations.AlterField(
            model_name='order',
            name='procedure_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
