# Generated by Django 3.2.6 on 2023-08-23 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_auto_20230823_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 17, 52, 27, 628365)),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
